name: Measure Docker Compose Startup Time

on:
  workflow_dispatch:

jobs:
  measure-startup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Measure Docker Compose Startup Time
        run: |
          start=$(date +%s)
          docker compose up -d
          end=$(date +%s)
          echo "Docker Compose stack started in $((end - start)) seconds."
          docker compose down