name: Staging Saleor-API Pipeline

on:
  push:
    branches:
       - staging
    paths:
      - 'saleor-api/**'

jobs:
  staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Docker Compose Services
        run: docker compose up -d --wait

      - name: Check Health of Services
        run: docker-compose ps | grep "(healthy)"

      - name: Stop Docker Compose
        if: always()
        run: docker compose down

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor-api:staging -f saleor-api/Dockerfile .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/saleor-api:staging